#!/usr/bin/env python3
"""Build index.md from the JSON-compatible YAML databases."""

from __future__ import annotations

import json
import re
from collections import defaultdict
from datetime import date, datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TODAY = date.today()


def load(path: str) -> dict:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def age_days(value: str) -> int:
    try:
        return (TODAY - datetime.strptime(value, "%Y-%m-%d").date()).days
    except (TypeError, ValueError):
        return 99999


def link(path: str, label: str) -> str:
    return f"[{label}]({path})"


def scan_visuals_and_tables() -> tuple[dict[str, int], dict[str, list[str]]]:
    visuals: dict[str, int] = {}
    tables: dict[str, list[str]] = {}
    table_pattern = re.compile(r"\b(TBL-[A-Z0-9-]+)\b")
    for path in ROOT.rglob("*.md"):
        rel = path.relative_to(ROOT).as_posix()
        if rel == "index.md":
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        visuals[rel] = text.count("```mermaid") + len(re.findall(r"!\[[^\]]*\]\(", text))
        tables[rel] = sorted(set(table_pattern.findall(text)))
    return visuals, tables


def main() -> None:
    techs = load("data/technology_taxonomy.yaml")["technologies"]
    vendor_data = load("data/vendor_roadmaps.yaml")
    vendors = vendor_data["vendors"]
    roadmaps = vendor_data["roadmap_items"]
    figures = load("data/figure_registry.yaml")["figures"]
    sources = load("data/source_database.yaml")["sources"]
    visuals, tables = scan_visuals_and_tables()
    generated_on = max([TODAY.isoformat()] + [item["last_refreshed"] for item in techs])

    by_category: dict[str, list[dict]] = defaultdict(list)
    by_application: dict[str, list[dict]] = defaultdict(list)
    by_year: dict[int, list[dict]] = defaultdict(list)
    by_relevance: dict[int, list[dict]] = defaultdict(list)
    for tech in techs:
        by_category[tech["category"]].append(tech)
        for app in tech["relevant_applications"]:
            by_application[app].append(tech)
        by_relevance[int(tech["Marvell_relevance_score"])].append(tech)
    for item in roadmaps:
        by_year[int(item["year"])].append(item)

    stale = []
    low_source = []
    insufficient_visuals = []
    for tech in techs:
        if age_days(tech["last_refreshed"]) > 90:
            stale.append((tech["name"], tech["profile_path"], tech["last_refreshed"]))
        if len(tech["source_ids"]) < 2:
            low_source.append((tech["name"], tech["profile_path"], len(tech["source_ids"])))
        if visuals.get(tech["profile_path"], 0) < 1 and not tech.get("figure_ids"):
            insufficient_visuals.append((tech["name"], tech["profile_path"]))

    lines = [
        "# Advanced Packaging Intelligence Index",
        "",
        f"Generated by `scripts/build_index.py` on {generated_on}.",
        "",
        "## Executive navigation",
        "",
        f"- {link('dashboard/index.html', 'Interactive executive presentation dashboard')}",
        f"- {link('dashboard/README.md', 'Dashboard user guide')}",
        f"- {link('reports/executive_summary_for_marvell_leadership.md', 'Executive summary for Marvell leadership')}",
        f"- {link('reports/advanced_packaging_main_report.md', 'Advanced packaging main report')}",
        f"- {link('reports/marvell_xpu_implications.md', 'Marvell custom XPU implications')}",
        f"- {link('reports/corp_dev_and_partnership_watchlist.md', 'Corporate development and partnership watchlist')}",
        f"- {link('assets/diagrams/mermaid_catalog.md', 'Visual catalog')}",
        "",
        "## Database summary",
        "",
        "| Record type | Count | Database |",
        "|---|---:|---|",
        f"| Technologies | {len(techs)} | {link('data/technology_taxonomy.yaml', 'taxonomy')} |",
        f"| Vendors | {len(vendors)} | {link('data/vendor_roadmaps.yaml', 'vendor roadmaps')} |",
        f"| Roadmap items | {len(roadmaps)} | {link('data/vendor_roadmaps.yaml', '2024-2030 roadmap')} |",
        f"| Sources | {len(sources)} | {link('data/source_database.yaml', 'source database')} |",
        f"| Figures | {len(figures)} | {link('data/figure_registry.yaml', 'figure registry')} |",
        f"| Indexed table IDs | {sum(len(value) for value in tables.values())} | Embedded in Markdown |",
        "",
        "## Technologies by category",
        "",
    ]
    for category in sorted(by_category):
        lines.append(f"### {category}")
        lines.append("")
        for tech in sorted(by_category[category], key=lambda item: item["name"]):
            lines.append(f"- {link(tech['profile_path'], tech['name'])} - maturity: {tech['maturity_level']}; Marvell relevance: {tech['Marvell_relevance_score']}/5; refreshed: {tech['last_refreshed']}")
        lines.append("")

    lines.extend(["## Vendors", ""])
    for vendor in sorted(vendors, key=lambda item: (item["category"], item["name"])):
        lines.append(f"- {link(vendor['profile_path'], vendor['name'])} - {vendor['category']}; relevance {vendor['Marvell_relevance']}/5; threat {vendor['competitive_threat']}/5")

    lines.extend(["", "## Applications", ""])
    for application in sorted(by_application):
        tech_links = ", ".join(link(item["profile_path"], item["name"]) for item in sorted(by_application[application], key=lambda item: item["name"]))
        lines.append(f"- **{application}:** {tech_links}")

    lines.extend(["", "## Roadmap by year", ""])
    for year in sorted(by_year):
        lines.append(f"### {year}")
        lines.append("")
        for item in by_year[year]:
            lines.append(f"- **{item['technology']} / {item['vendor']}:** {item['claimed_capability']} - `{item['status']}`, confidence `{item['confidence_level']}`, Marvell relevance `{item['Marvell_relevance']}`.")
        lines.append("")

    lines.extend(["## Technologies by Marvell relevance", ""])
    for score in sorted(by_relevance, reverse=True):
        tech_links = ", ".join(link(item["profile_path"], item["name"]) for item in sorted(by_relevance[score], key=lambda item: item["name"]))
        lines.append(f"- **{score}/5:** {tech_links}")

    lines.extend(["", "## Figures", ""])
    for figure in figures:
        lines.append(f"- **{figure['figure_id']} - {figure['title']}:** {link(figure['local_path'], figure['local_path'])}; {figure['source_type']}.")

    lines.extend(["", "## Tables", ""])
    for path, ids in sorted(tables.items()):
        if ids:
            lines.append(f"- {link(path, path)}: {', '.join(ids)}")

    lines.extend(["", "## Refresh flags", ""])
    lines.append(f"- **Stale profiles (>90 days):** {len(stale)}")
    for name, path, refreshed in stale:
        lines.append(f"  - {link(path, name)} - last refreshed {refreshed}")
    lines.append(f"- **Low source count (<2):** {len(low_source)}")
    for name, path, count in low_source:
        lines.append(f"  - {link(path, name)} - {count} source(s)")
    lines.append(f"- **Insufficient visuals:** {len(insufficient_visuals)}")
    for name, path in insufficient_visuals:
        lines.append(f"  - {link(path, name)}")

    lines.extend([
        "",
        "## Refresh and validation",
        "",
        f"- {link('scripts/refresh_section_template.md', 'Section refresh workflow')}",
        f"- {link('scripts/refresh_full_database_template.md', 'Full database refresh workflow')}",
        "- Run `python3 scripts/build_dashboard.py` after database changes.",
        "- Run `python3 scripts/validate_database.py`.",
        "- Run `python3 scripts/build_index.py` after every material update.",
    ])
    (ROOT / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Built index.md with {len(techs)} technologies, {len(vendors)} vendors, {len(figures)} figures and {sum(len(value) for value in tables.values())} table IDs.")


if __name__ == "__main__":
    main()
